modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="raidborn"
version="0.1-1.20.1"
displayName="Raidborn: Ally with Illagers"
authors="Randomcara7 and I_DRAW_THINGS"
description='''Join the wrong side'''

[[dependencies.raidborn]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.raidborn]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.raidborn]]
modId="bentoslib"
mandatory=true
versionRange="[0.1,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.raidborn]]
modId="curios"
mandatory=true
versionRange="[5.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.raidborn]]
modId="patchouli"
mandatory=false
versionRange="[1.20.1-84,)"
ordering="AFTER"
side="BOTH"

[[dependencies.raidborn]]
modId="jei"
mandatory=false
versionRange="[15.0.0,)"
ordering="AFTER"
side="BOTH"
